# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CO9lb2mKbq_42N565DN_05QdpDe7EOFL
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

#reading dataset
netflix = pd.read_csv("netflix_titles.csv")
print(netflix.head())
print(netflix.columns)

#movies vs tvshows
movies = netflix['type'].value_counts()
print(movies.head(2))
#plotting graph
movies.head(2).plot(kind='bar')
plt.title("Movies vs tv shows")
plt.xlabel("type")
plt.ylabel("count")
plt.show()

#analyzing top 5 genres
genre = netflix['listed_in'].str.split(', ')
genre = genre.explode()
top_genre=genre.value_counts()
print(top_genre.head(5))
#plotting
top_genre.head(5).plot(kind='bar')
plt.title("Top genres")
plt.xlabel("genre")
plt.ylabel("count")
plt.show()

#content over yeras
year = netflix['release_year'].value_counts().sort_index()
print(year.head())

#line graph
year.plot(kind='line')
plt.title("Content over years")
plt.xlabel("year")
plt.ylabel("No of shows")
plt.show()

#analyzing country of origin of show
country = netflix['country'].str.split(',')
country = country.explode()
top_country = country.value_counts()
print(top_country.head(5))

#plotting graph
top_country.head(5).plot(kind='bar')
plt.title("Top countries")
plt.xlabel("country")
plt.ylabel("No of shows")
plt.show()